version: 0.2
phases:
  pre_build:
    commands:
      - echo "Login to Amazon ECR Start...."
      - aws --version
      - echo "Logging in to Amazon ECR...."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 905418027533.dkr.ecr.us-east-1.amazonaws.com
      - echo "Login to Amazon ECR Completed...."
      - echo "Repository URI"
      - RepositoryURI=905418027533.dkr.ecr.us-east-1.amazonaws.com/hello-shoes-server
      - echo "Setting Image Tag"
      - IMAGE_TAG=$(echo $CODEBUILD_ID | awk -F":" '{print $2}')
      - echo "Setting Image Tag Completed"
  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean install
      - echo "Building the Docker image..."
      - docker build -t $RepositoryURI:latest .
      - echo "Tagging the Docker image..."
      - docker tag $RepositoryURI:latest $RepositoryURI:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing the Docker images..."
      - docker push $RepositoryURI:latest
      - docker push $RepositoryURI:$IMAGE_TAG
      - echo "Build completed on `date`"
      - DOCKER_CONTAINER_NAME=shoe-server-app
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $RepositoryURI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    artifacts:
      files:
        - imagedefinitions.json
        - target/shoe-server-app.jar